* Setting up Emacs
2015 Sandor Juhasz

** Overview
This document describes the step-by-step process of setting up a new
installation of emacs and other external tools to get a fully
functional Clojure and note taking environment.

** Installation

*** Total Commander
Use the following command as an external editor to use Emacs when you
edit files in Total Commander. Please Use the quotation marks,
otherwise your files will open in Emacs with their old 8.3 DOS
filenames.

#+BEGIN_EXAMPLE
"c:\Dev\Apps\emacs-24.4\bin\emacsclientw.exe"  -na "C:\Dev\Apps\emacs-24.4\bin\runemacs.exe"
#+END_EXAMPLE

*** Java SE 8
*** wget
*** leiningen
Cider requires the `cider-nrepl` plugin and the most recent nrepl.
To add this to your configuration, edit your ~/.lein/profiles.clj file.
My version looks like this:

{:user {:plugins [[cider/cider-nrepl "0.9.0-SNAPSHOT"]
                  [lein-pprint "1.1.2"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.10"]]}}

As of May 1st 2015, with Leiningen 2.5.1 it is a known issue that if you start 
cider-jack-in from outside a project, the repl will use the default 0.2.6
tools.nrepl dependency, no matter what you set in the profiles.clj.
This will lead to a warning when you start a repl from Emacs. To use the
most recent version of the nrepl, please invoke cider-jack-in after you
opened a Clojure project file.

*** git
*** hunspell
Download the windows version of hunspell from
http://sourceforge.net/projects/ezwinports/files/hunspell-1.3.2-3-w32-bin.zip/download
and extract it under the gnuwin32 directory. For me this is
c:\dev\apps\gnuwin32. Test the hunspell installation by invoking
hunspell -D. This command should list all the dictionaries installed
on your system.

Open the global environment variable dialog and set the LANG variable
to en_US. 

When invoking ispell from Emacs, you may get the following error:
"ispell-phaf: No matching entry for nil". This may be caused by a
wrong default value of the LANG variable. For me Emacs set it to HUN
which was something huspell could not interpret.


*** installing the init.el

** Configuration and usage

*** Clojure development with Cider

**** Modes, plugins I use
- Paredit
- Rainbow delimiters
- clojure mode, cider
- magit

*** Authoring text in org mode

